#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lenombrealeatoire :
    path : /nombre/aleatoire
    controller : App\Controller\TestController::nbaleatoire
    
    
    
   
maintenant :
    path : /date/maintenant
    controller : App\Controller\TestController::dateMaintenant


base :
    path : /base
    controller : App\Controller\TestController::base